CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_TIMEOUT=60000

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_TEXT_ALIGN="right"
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_NAME_SCROLL_WIDTH=75