# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT
### -----------------------------------------
### Peripherals
# Encoder Support
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Mouse Emulation
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Backlight
CONFIG_ZMK_BACKLIGHT=y
CONFIG_ZMK_BACKLIGHT_BRT_STEP=20

# Debounce (Lower Input Lag)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

### -----------------------------------------
### Power
# External
CONFIG_ZMK_EXT_POWER=y
# Battery Reporting
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

### -----------------------------------------
### ZMK Studio
CONFIG_ZMK_STUDIO=y

### -----------------------------------------
### MACRO MEMES
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512
