manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: honeycat
      url-base: https://github.com/H0N3YC4T
  projects:
    - name: zmk-dongle-display
      remote: englmaxi
      revision: 2bb333f87136d33e94a49d86236ed9ec254a8060
    - name: zmk
      remote: honeycat
      revision: 0cb08f0c82dc20c3e068c17557b3cbcb12379ad5
      import: app/west.yml
    - name: dongle-mk1
      remote: honeycat
      revision: main
    - name: nice-view-mk1
      remote: honeycat
      revision: main
  self:
    path: config
