# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

### -----------------------------------------
### Power
# Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1200000
CONFIG_ZMK_IDLE_TIMEOUT=180000

### -----------------------------------------
### OLED DISPLAY
# Custom Display
CONFIG_ZMK_DISPLAY=y
CONFIG_NICE_VIEW_ANIMATION=y
CONFIG_NICE_VIEW_ANIMATION_MS=330000

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

