# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT
### -----------------------------------------
### BASIC
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

### Power
# Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1200000
CONFIG_ZMK_IDLE_TIMEOUT=180000
CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y

### -----------------------------------------
### OLED DISPLAY
# Custom Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_VIEW_ANIMATION=y
CONFIG_NICE_VIEW_ANIMATION_MS=330000
CONFIG_NICE_VIEW_ANIMATION_THEME_TRANSMUTATION=y
### -----------------------------------------
### Bluetooth
# Power Boost
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y



# Backlight
CONFIG_ZMK_BACKLIGHT=y
CONFIG_ZMK_BACKLIGHT_BRT_STEP=20
